language: rust
rust:
  - nightly
cache: cargo
before_script: (cargo install rustfmt || true)
script:
- |
  export PATH=$PATH:~/.cargo/bin &&
  cargo fmt -- --write-mode=diff &&
  cargo build &&
  cargo test
matrix:
  allow_failures:
    - rust: nightly